### ISSUE TITLE
Cactbot URLs need to be updated to new cactbot github

### ISSUE THREAD

**Issue by litori** [marzent/Bunny-HUD#11]
The cactbot github moved and it is still pointing to the dead repo.  The cactbot settings page is stuck on blank.  Can we please have this updated?

**Comment by seathasky** [comment]
Wrong github possibly? 

Maybe you meant IINACT? (Btw these are already working just fine and we've already updated the IINACT proxies)

**Comment by zebe** [comment]
Same as #4 and #8 ?

**Comment by seathasky** [comment]
All act sources have been updated. If you are not seeing Cactbot, CMD+R on Bunnyhud's main screen to reload all overlays or restart IINACT.

<img width="1800" alt="Image" src="https://github.com/user-attachments/assets/2420d0f1-e950-4b53-b714-8ab828ae3edd" />

**Comment by sarconus** [comment]
![Image](https://github.com/user-attachments/assets/cc8c5711-4607-4446-99ea-5aed3da9141e)

The overlay urls are incorrect.  Which causes a blank screen on the bunnyhud cactbot config page.  The iinact overlay urls were updated to point to the new repo.

**Comment by sarconus** [comment]
The new urls should be: 

http://proxy.iinact.com/overlay/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws

If new user sets up bunnyhud, it would not work for them.  Probably still works for users before the repo moved.  All new setups currently get a blank page and broken cactbot since the URLs are hard coded in bunnyhud.

**Comment by seathasky** [comment]
> The new urls should be:
> 
> http://proxy.iinact.com/overlay/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws
> 
> If new user sets up bunnyhud, it would not work for them. Probably still works for users before the repo moved. All new setups currently get a blank page and broken cactbot since the URLs are hard coded in bunnyhud.

All our proxies are hard coded into every URL you are seeing. They are in a json inside our app package. If you are struggling to run Cactbot, A:) you're using a VPN.  B:) You need to restart/update IINACT or reload overlays in BunnyHud. 

The reason you are unable to see the cactbot config has nothing to do with the proxies. You can open the config information by pasting: http://proxy.iinact.com/overlay/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws into your web browser. There is nothing wrong with BunnyHuds proxy information though. It is likely another issue we need to look into.

**Comment by sarconus** [comment]
The http://proxy.iinact.com/overlay/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws works fine in the browser.  The one inside bunnyhud that points to quisquous.github.io does not.

**Comment by seathasky** [comment]
> The http://proxy.iinact.com/overlay/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws works fine in the browser. The one inside bunnyhud that points to quisquous.github.io does not.

Read what I posted again, it's not a proxy address issue. Our proxies have never once changed since we set them up. The proxy clearly works in a web browser. The quisquous visual url in bunnyhud has zero relevance on what we're actually using in the json file. Cactbot would not work otherwise.

I get you're trying to help, but i've already told you that the visual URL is not the issue.

<img width="876" alt="Image" src="https://github.com/user-attachments/assets/fdc91fbe-c086-47a2-bd3b-93adf4358aec" />

**Comment by sarconus** [comment]
It may be because when you try to load 

https://quisquous.github.io/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws
it now redirects to 
https://overlayplugin.github.io/cactbot/ui/config/config.html

which bunnyhud does not forward the "?OVERLAY_WS=ws://127.0.0.1:10501/ws" to the new url.  Loading https://overlayplugin.github.io/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws directly works.

**Comment by seathasky** [comment]
> It may be because when you try to load
> 
> https://quisquous.github.io/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws it now redirects to https://overlayplugin.github.io/cactbot/ui/config/config.html
> 
> which bunnyhud does not forward the "?OVERLAY_WS=ws://127.0.0.1:10501/ws" to the new url. Loading https://overlayplugin.github.io/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws directly works.

All our overlay urls are setup here: https://github.com/cking/act-overlays 

I've already made the changes here: https://github.com/cking/act-overlays/pull/5/files

That should fix the config not showing when it's committed. @marzent  will still need to update Bunnyhud to support version 2 because it's currently using version 1 of these act-overlays. He'll get around to it when he can

**Comment by sarconus** [comment]
I see that the cking has merged the pull request but bunnyhud still showing the old url after close and reopen.  How do you trigger it to load the new json?

**Comment by seathasky** [comment]
> I see that the cking has merged the pull request but bunnyhud still showing the old url after close and reopen. How do you trigger it to load the new json?

That's because we still need to update Bunnyhud with these changes, should be done soon TM.

**Comment by seathasky** [comment]
@litori https://github.com/marzent/Bunny-HUD/commit/faaae155a4151b0b4c7aa94e4332900c91213122

closing this

**Comment by seathasky** [comment]
<img width="1513" alt="Image" src="https://github.com/user-attachments/assets/d9c6a5a1-034a-43d8-bd90-e0557873989a" />
